### ISSUE TITLE
Login and OPF creation not working

### ISSUE THREAD

**Issue by guzzo-zz** [nicjansma/economist-to-kindle#1]
Let me just say that I am so glad I found this script. I recently got a Kindle and have been searching ever since how to get the Economist onto it. Unfortunately, the Kindle editions published on Amazon aren't available where I live (Australia) and so I'm left with no recourse, despite having a subscription. Annoying right?

Anyway, to the heart of the problem. I'm not at all experienced with scripting, but it seems to me that some header formatting or something has changed on the Economist's website that the login function is no longer working. As for why the OPF file isn't getting made properly, I have no idea...

Here's the relevant output from running the script (the first two lines):
Economist ="n xmlns="http://www.w3.org/1999/xhtm, xml:lang="en" (xml:lang="en"0x)
Creating OPF file: economist_xml:lang="en"0x.opf... done!

I'm running the script on Windows 7. Also, does that means I have to flip all the directory references from /'s to \'s? Or else is there someway to run the script in a Linux environment on Windows, if that would be easier?

Thanks for any help!

**Comment by nicjansma** [comment]
HI guzzo,

I believe I fixed this with my most recent update.

Let me know if you see any further issues!

**Comment by guzzo-zz** [comment]
Thanks Nic! Works brilliantly now: I just had to swap some /s to \s at the date directory and opf creation lines, flip the context for mobi conversion with kindlegen (which for some reason gives a lot of warnings...), throw in some quotes and the script was good to go.
Cheers,
Guzzo
