### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by guzzo-zz** [nicjansma/economist-to-kindle#2]
Hey Nic,
Sorry to bug you again, but is there anything I need to do apart from putting in the to and from emails into the script for the emailing to work? I'm using my gmail address, which has https as standard, and is on the Kindle's white list... Any ideas?
Thanks again!
Guzzo

**Comment by nicjansma** [comment]
That's all you should need to do, but I haven't configured it on Windows before.

**Comment by guzzo-zz** [comment]
Hey Nic,
It's all sorted now; it was just a matter of defining a SMTP server in the php.ini
Thanks again for the awesome script!
