### ISSUE TITLE
Progress bar and location absent

### ISSUE THREAD

**Issue by guzzo-zz** [nicjansma/economist-to-kindle#3]
Hey Nic,
So for the last few .mobi files that have been churned out by the script, the percentage read and location numbers have been absent - the last issue that still had these features was from February 4. Do you have any idea what the problem could be?
(EDIT: if it's of any assistance, the location numbers come up if I open the .mobi file in Kindle for PC.)
(EDIT #2: I tested the problem by sending a text-only version of the latest Economist and the problem is solved. This leads me to believe that the size of the mobi file involved has something to do with it. Maybe having the pictures converted into grey-scale would downsize them and fix the problem?)
Also, could I make a suggestion for possible formatting improvements? I don't have any idea how feasible this is, or how much work would be involved, but would it be possible to make the output of each edition have progress bars for each article and a larger-format table of contents (à la Instapaper article summaries sent to Kindle)?
Cheers, and Happy Easter,
Guzzo

**Comment by nicjansma** [comment]
Around that time, I had to make some major changes to the script to get it working with their new site (https://github.com/nicjansma/economist-to-kindle/commit/6d497641e52d7fba99fccb561df85585ed9c8f77).  But I don't believe any of the changes would have affected the percentage read indicator.  You're speaking of the percentage read indicator on your hardware Kindle, correct?  What version?

I'm not seeing this issue on Mobipocket Reader or Kindle for PC.  I'm not sure why it wouldn't work on Kindle for PC.

Unfortunately, I don't know how to have progress bars for each article.  Maybe someone else does?

**Comment by guzzo-zz** [comment]
Yes, I remember the changes in the website format, that may well be the
issue.
And yes, I mean the percentage read indicator on the hardware Kindle - the
problem is quickly resolved when viewing the articles on Kindle for PC.
I've got the Kindle Touch, firmware recently updated to v5.1.0 (the problem
has persisted since the update).
Maybe the problem has got to do with the .mobi file creation on my computer
- whenever I run the script, the file coming out of KindleGen is always
  reported to have been made 'with warnings'.
  Anyway, I'll keep investigating. Thanks for the response!

On Tue, May 15, 2012 at 6:31 AM, Nic Jansma <
reply@reply.github.com
