### ISSUE TITLE
Latest Economist.com Update

### ISSUE THREAD

**Issue by guzzo-zz** [nicjansma/economist-to-kindle#4]
Hey Nic,
It seems like perhaps the website has been updated again, as the script is no longer working for me. My last successful issue was early October, if that's any assistance.
Cheers,
Guzzo

**Comment by nicjansma** [comment]
Pretty simple fix this time, the URL structure has changed.  I was able to get it working again.

b38e016344608812ed98a0f8787d6ceb99373169
